feat: better deployment handling

diff --git a/bin/build_and_deploy b/bin/build_and_deploy
--- a/bin/build_and_deploy
+++ b/bin/build_and_deploy
@@ -55,7 +55,7 @@ Restart=on-failure
 TimeoutStopSec=35
 ExecStartPre=rm -f %t/%n-pid %t/%n-cid
 ExecStartPre=podman load --input \${HOME}/${DEPLOY_IMAGE_ARCHIVE}/${IMAGE_BASE_NAME}.tar
-ExecStart=podman run -t -d --name ${SERVICE_NAME} --read-only --replace --restart=on-failure:3 --env-file \${HOME}/${DEPLOY_ENV}/${SERVICE_NAME} --mount type=bind,src=\${HOME}/${DEPLOY_PERSISTENT_DATA}/${SERVICE_NAME},dst=/data --userns keep-id:uid=65532,gid=65532 --log-driver=k8s-file --log-opt max-size=128kb,path=\${HOME}/${DEPLOY_LOGS}/${SERVICE_NAME}/lastest.log --hostname ${SERVICE_NAME}.svc.${DEPLOY_HOST} --publish ${SERVICE_PORT}:${SERVICE_PORT}/tcp --conmon-pidfile %t/%n-pid --cidfile %t/%n-cid ${FULL_IMAGE_NAME} ${SERVICE_ARGUMENTS}
+ExecStart=podman run -d --name ${SERVICE_NAME} --read-only --replace --restart=on-failure:3 --env-file \${HOME}/${DEPLOY_ENV}/${SERVICE_NAME} --mount type=bind,src=\${HOME}/${DEPLOY_PERSISTENT_DATA}/${SERVICE_NAME},dst=/data --userns keep-id:uid=65532,gid=65532 --network slirp4netns:allow_host_loopback=true --log-driver=k8s-file --log-opt max-size=128kb,path=\${HOME}/${DEPLOY_LOGS}/${SERVICE_NAME}/latest.log --hostname ${SERVICE_NAME}.svc.${DEPLOY_HOST} --publish [::1]:${SERVICE_PORT}:${SERVICE_PORT}/tcp --conmon-pidfile %t/%n-pid --cidfile %t/%n-cid ${FULL_IMAGE_NAME} ${SERVICE_ARGUMENTS}
 # We match the k8s container behavior of 30 seconds to kill
 ExecStop=podman stop -t 30 --cidfile %t/%n-cid
 PIDFile=%t/%n-pid
@@ -88,68 +88,76 @@ nohup sh -c "\
   cp -f "${DEPLOY_SERVICE_DIRECTORY}/${SERVICE_NAME}/${VERSIONED_SVC_NAME}.service" "\${HOME}/.config/systemd/user/${SERVICE_NAME}.service"
   systemctl --user daemon-reload
 
-  if systemctl --user is-active --quiet ${SERVICE_NAME}.service; then
-    echo '##> Service is running, attempting a restart...'
+  if systemctl --user is-enabled --quiet ${SERVICE_NAME}.service; then
+    echo '##> Service is enabled lets meddle...'
 
-    if ! systemctl --user restart ${SERVICE_NAME}.service &>/dev/null; then
-      echo '##> Service failed to start...'
+    if systemctl --user is-active --quiet ${SERVICE_NAME}.service; then
+      echo '##> Service is running, attempting a restart...'
 
-      if [ -L "${DEPLOY_STATE}/${SERVICE_NAME}.service" ]; then
-        echo '##> Previous version available, attempting to revert...'
+      if ! systemctl --user restart ${SERVICE_NAME}.service &>/dev/null; then
+        echo '##> Service failed to start...'
 
-        cp -Lf "${DEPLOY_STATE}/${SERVICE_NAME}.service" "\${HOME}/.config/systemd/user/${SERVICE_NAME}.service"
+        if [ -L "${DEPLOY_STATE}/${SERVICE_NAME}.service" ]; then
+          echo '##> Previous version available, attempting to revert...'
 
-        systemctl --user daemon-reload
-        systemctl --user restart ${SERVICE_NAME}.service
+          cp -Lf "${DEPLOY_STATE}/${SERVICE_NAME}.service" "\${HOME}/.config/systemd/user/${SERVICE_NAME}.service"
 
-        echo '##> Reverted successfully'
-      else
-        echo '##> No recovery version available'
+          systemctl --user daemon-reload
+          systemctl --user restart ${SERVICE_NAME}.service
+
+          echo '##> Reverted successfully'
+        else
+          echo '##> No recovery version available'
+        fi
+
+        echo '##> Deploy failed'
+
+        exit 1
       fi
 
-      echo '##> Deploy failed'
+      if ! curl -fqs http://127.0.0.1:${SERVICE_PORT}/_status/healthz >/dev/null; then
+        echo '##> Service failed to become healthy...'
 
-      exit 1
-    fi
+        if [ -L "${DEPLOY_STATE}/${SERVICE_NAME}.service" ]; then
+          echo '##> Previous version available, attempting to revert...'
 
-    if ! curl -fqs http://127.0.0.1:${SERVICE_PORT}/_status/healthz >/dev/null; then
-      echo '##> Service failed to become healthy...'
+          cp -Lf "${DEPLOY_STATE}/${SERVICE_NAME}.service" "\${HOME}/.config/systemd/user/${SERVICE_NAME}.service"
 
-      if [ -L "${DEPLOY_STATE}/${SERVICE_NAME}.service" ]; then
-        echo '##> Previous version available, attempting to revert...'
+          systemctl --user daemon-reload
+          systemctl --user restart ${SERVICE_NAME}.service
 
-        cp -Lf "${DEPLOY_STATE}/${SERVICE_NAME}.service" "\${HOME}/.config/systemd/user/${SERVICE_NAME}.service"
+          echo '##> Reverted successfully'
+        else
+          echo '##> No recovery version available'
+        fi
 
-        systemctl --user daemon-reload
-        systemctl --user restart ${SERVICE_NAME}.service
+        echo '##> Deploy failed'
 
-        echo '##> Reverted successfully'
-      else
-        echo '##> No recovery version available'
+        exit 2
       fi
 
-      echo '##> Deploy failed'
+      systemctl --user enable ${SERVICE_NAME}.service
 
-      exit 2
+      echo '##> Service appears to be healthy'
+    else
+      echo '##> Attempting to start failed service...'
+      systemctl --user start ${SERVICE_NAME}.service &>/dev/null
+      echo '##> Service successfully started'
     fi
 
-    systemctl --user enable ${SERVICE_NAME}.service
+    echo '##> Marking the new version as the "current" version'
 
-    echo '##> Service appears to be healthy'
+    if [ -L "${DEPLOY_STATE}/${SERVICE_NAME}.service" ]; then
+      mv "${DEPLOY_STATE}/${SERVICE_NAME}.service" "${DEPLOY_STATE}/${SERVICE_NAME}.service.last"
+    fi
+
+    ln -frs "${DEPLOY_SERVICE_DIRECTORY}/${SERVICE_NAME}/${VERSIONED_SVC_NAME}.service" "${DEPLOY_STATE}/${SERVICE_NAME}.service"
+
+    echo '##> Cleaning up old images...'
+    podman image prune -f
   else
-    echo 'Service isnt active not restarting...'
+    echo '##> Service isnt enabled not starting...'
   fi
-
-  echo '##> Marking the new version as the "current" version'
-
-  if [ -L "${DEPLOY_STATE}/${SERVICE_NAME}.service" ]; then
-    mv "${DEPLOY_STATE}/${SERVICE_NAME}.service" "${DEPLOY_STATE}/${SERVICE_NAME}.service.last"
-  fi
-
-  ln -frs "${DEPLOY_SERVICE_DIRECTORY}/${SERVICE_NAME}/${VERSIONED_SVC_NAME}.service" "${DEPLOY_STATE}/${SERVICE_NAME}.service"
-
-  echo '##> Cleaning up old images...'
-  podman image prune -f
 "
 EOS
 echo '==> Deployed'
