closer to a direct build and deploy system

diff --git a/bin/build_and_deploy b/bin/build_and_deploy
--- a/bin/build_and_deploy
+++ b/bin/build_and_deploy
@@ -20,42 +20,137 @@ NAMESPACE="sstelfox"
 IMAGE="${SERVICE_NAME}"
 
 DEPLOY_IMAGE_ARCHIVE="${DEPLOY_BASE_FOLDER}/library"
+DEPLOY_ENV="${DEPLOY_BASE_FOLDER}/env"
 DEPLOY_PERSISTENT_DATA="${DEPLOY_BASE_FOLDER}/data"
 DEPLOY_SERVICE_DIRECTORY="${DEPLOY_BASE_FOLDER}/services"
+DEPLOY_STATE="${DEPLOY_BASE_FOLDER}/state"
 
 COMMIT_ID="$(git describe --always --dirty --long --tags)"
-TIMESTAMP="$(date -u +%Y%m%d-%H%M%S%z | tr '+' '-')"
+TIMESTAMP="$(date -u +%Y%m%d-%H%M%S | tr '+' '-')"
 
 IMAGE_BASE_NAME="${NAMESPACE}_${IMAGE}_${TIMESTAMP}_${COMMIT_ID}"
 FULL_IMAGE_NAME="${REPOSITORY_HOST}/${NAMESPACE}/${IMAGE}:${COMMIT_ID}"
 
+TMP_IMAGE="$(mktemp /tmp/svc_img.XXXXX.tar)"
+
 # Create the actual container
 podman build -t ${FULL_IMAGE_NAME} ./
-podman save -o target/${IMAGE_BASE_NAME}.tar ${FULL_IMAGE_NAME}
+podman save -o ${TMP_IMAGE} ${FULL_IMAGE_NAME}
+echo 'Image successfully built and saved'
 
-# Ensure the place we store our service configs are present
-mkdir -p configs
-cd configs
+TEMP_DIR="$(mktemp -d /tmp/svc_pod.XXXXX)"
+VERSIONED_SVC_DIR="${SERVICE_NAME}-${TIMESTAMP}-${COMMIT_ID}"
+CONFIG_DIR="${TEMP_DIR}/${VERSIONED_SVC_DIR}"
 
-podman pod create --name=${SERVICE} -h ${SERVICE}.services.stelfox.net \
-  --security-opt=label=disable --network=pasta:-T,${SERVICE_PORT}
+mkdir -p ${CONFIG_DIR}
+cd ${CONFIG_DIR}
+
+DEPENDENT_SERVICES="${SERVICE_NAME}-api-http.service"
 
 if [ "${SERVICE_NEEDS_POSTGRES}" = "true" ]; then
-  podman create --pod=${SERVICE} --name=db-postgres -e POSTGRES_PASSWORD \
-    -t repo.stelfox.net/library/postgres:alpine
+  DEPENDENT_SERVICES="${DEPENDENT_SERVICES} ${SERVICE_NAME}-db-postgres.service"
 fi
 
-podman create --pod=${SERVICE} --name=api-http -e POSTGRES_PASSWORD \
-  -t ${FULL_IMAGE_NAME}
+cat << EOS > ${SERVICE_NAME}.service
+[Unit]
+Description=${SERVICE_NAME}
+Wants=network-online.target
+After=network-online.target
+Wants=${DEPENDENT_SERVICES}
+Before=${DEPENDENT_SERVICES}
 
-podman generate systemd --files --name=${SERVICE} --pod-prefix "" \
-  --container-prefix ${SERVICE}
+[Service]
+Restart=on-failure
+TimeoutStopSec=30
+ExecStartPre=podman pod create --name=${SERVICE_NAME} -h ${SERVICE_NAME}.services.stelfox.net --exit-policy stop --network=pasta:-T,3000 --restart=on-failure:3 --replace
+ExecStart=podman pod start ${SERVICE_NAME}
+ExecStop=podman pod stop -t 10 ${SERVICE_NAME}
+Type=forking
+EOS
 
-podman pod rm ${SERVICE}
+if [ "${SERVICE_NEEDS_POSTGRES}" = "true" ]; then
+  cat << EOS > ${SERVICE_NAME}-db-postgres.service
+[Unit]
+Description=${SERVICE_NAME} Database (PostgreSQL)
+Wants=network-online.target
+After=network-online.target
+BindsTo=${SERVICE_NAME}.service
+After=${SERVICE_NAME}.service
+
+[Service]
+Restart=on-failure
+TimeoutStopSec=30
+EnvironmentFile-=${DEPLOY_ENV}/${SERVICE_NAME}
+EnvironmentFile-=${DEPLOY_ENV}/${SERVICE_NAME}.db
+ExecStartPre-=podman rm -f ${SERVICE_NAME}-db-postgres
+ExecStart=podman run --pod ${SERVICE_NAME} -d --name ${SERVICE_NAME}-db-postgres docker.io/library/postgres:alpine
+ExecStop=podman stop --pod ${SERVICE_NAME} -t 10 --name ${SERVICE_NAME}-db-postgres
+EOS
+fi
+
+cat << EOS > ${SERVICE_NAME}-api-http.service
+[Unit]
+Description=${SERVICE_NAME} HTTP API
+Wants=network-online.target
+After=network-online.target
+BindsTo=${SERVICE_NAME}.service
+After=${SERVICE_NAME}.service
+
+[Service]
+Restart=on-failure
+TimeoutStopSec=30
+EnvironmentFile-=${DEPLOY_ENV}/${SERVICE_NAME}
+EnvironmentFile-=${DEPLOY_ENV}/${SERVICE_NAME}.api
+ExecStartPre=podman load -q --input=${DEPLOY_IMAGE_ARCHIVE}/${IMAGE_BASE_NAME}.tar
+ExecStartPre-=podman rm -f ${SERVICE_NAME}-api-http
+ExecStart=podman run --pod ${SERVICE_NAME} --name ${SERVICE_NAME}-api-http ${FULL_IMAGE_NAME}
+ExecStop=podman stop --pod ${SERVICE_NAME} -t 10 --name ${SERVICE_NAME}-api-http
+EOS
 
 # Transfer the container archive to the remote host
-ssh ${REMOTE_HOST} "mkdir -p ${DEPLOY_IMAGE_ARCHIVE} ${DEPLOY_SERVICE_DIRECTORY}"
-scp -O target/${IMAGE_BASE_NAME}.tar ${REMOTE_HOST}:${REMOTE_IMAGE_ARCHIVE}/
+ssh ${DEPLOY_HOST} "mkdir -p ${DEPLOY_IMAGE_ARCHIVE} ${DEPLOY_ENV} ${DEPLOY_PERSISTENT_DATA} ${DEPLOY_SERVICE_DIRECTORY} ${DEPLOY_STATE}"
+scp -O ${TMP_IMAGE} ${DEPLOY_HOST}:${DEPLOY_IMAGE_ARCHIVE}/${IMAGE_BASE_NAME}.tar
+rsync -avrz -h --progress ${CONFIG_DIR}/ ${DEPLOY_HOST}:${DEPLOY_SERVICE_DIRECTORY}/${VERSIONED_SVC_DIR}
+echo 'Deployed version transferred to service host'
+
+ssh -T ${DEPLOY_HOST} <<EOS
+nohup sh -c "\
+  set -o errexit
+
+  mkdir -p "${DEPLOY_STATE}"
+
+  echo 'Overwriting current version with new service data...'
+  mkdir -p "\${HOME}/.config/systemd/user"
+  cp -f "${DEPLOY_SERVICE_DIRECTORY}/${VERSIONED_SVC_DIR}/*.service" "\${HOME}/.config/systemd/user/"
+  systemctl --user daemon-reload
+
+  if systemctl is-active --quiet ${SERVICE_NAME}.service; then
+    echo 'Service is running, attempting a restart...'
+
+    if ! systemctl --user restart ${SERVICE_NAME}.service &>/dev/null; then
+      echo 'Service failed attempting to revert...'
+
+      cp -f "${DEPLOY_STATE}/${SERVICE_NAME}/*.service" "\${HOME}/.config/systemd/user/"
+      systemctl --user daemon-reload
+      systemctl --user restart ${SERVICE_NAME}.service
+
+      echo 'Reverted successfully'
+      exit 1
+    fi
+  fi
+
+  echo 'Marking new service as current...'
+  #if [ -L "${DEPLOY_STATE}/${SERVICE_NAME}" ] && mv "${DEPLOY_STATE}/${SERVICE_NAME}{,_last}"
+  #ln -s "${DEPLOY_SERVICE_DIRECTORY}/${VERSIONED_SVC_DIR}" -t "${DEPLOY_STATE}" "${SERVICE_NAME}"
+"
+EOS
+echo 'deployed'
+
+# cp * $HOME/config/systemd/user
+# systemctl --user start web-app-template.service
+# rm "$SERVER_PATH/$BINARY_NAME"
+# ln -s "$SERVER_PATH/versions/$REMOTE_FILENAME" "$SERVER_PATH/$BINARY_NAME"
+# $SERVER_RESTART_COMMAND
 
 # Repo setup:
 #
@@ -134,7 +229,7 @@ scp -O target/${IMAGE_BASE_NAME}.tar ${REMOTE_HOST}:${REMOTE_IMAGE_ARCHIVE}/
 # Generate podman container definitions:
 #
 # ```
-# podman pod create --name=${SERVICE} -h web-app-template.service.stelfox.net --security-opt=label=disable --network=pasta:-T,3000
+# podman pod create --name=${SERVICE} -h web-app-template.service.stelfox.net --security-opt=label=disable --network=pasta:-T,${SERVICE_PORT}
 # podman create --pod=web-app-template --name=db-postgres -e POSTGRES_PASSWORD=test_password -t repo.stelfox.net/library/postgres:alpine
 # podman create --pod=web-app-template --name=api-http -e POSTGRES_PASSWORD=test_password -t repo.stelfox.net/sstelfox/web-app-template:latest
 #
